INSERT INTO subway_stations (
    complex_id,
    is_complex,
    number_of_stations_in_complex,
    stop_name,
    display_name,
    constituent_station_names,
    station_ids,
    gtfs_stop_ids,
    borough,
    cbd,
    daytime_routes,
    structure_type,
    latitude,
    longitude,
    ada,
    ada_notes
)
SELECT
    complex_id::NUMERIC,
    is_complex,
    number_of_stations_in_complex,
    stop_name,
    display_name,
    constituent_station_names,
    station_ids,
    gtfs_stop_ids,
    borough,
    cbd,
    daytime_routes,
    structure_type,
    latitude::NUMERIC,
    longitude::NUMERIC,
    POINT(latitude::NUMERIC, longitude::NUMERIC) as georeference
    ada,
    ada_notes
FROM
    subway_stations_staging;